theme: jekyll-theme-hacker
url: "http://teeekay.tknights.com"
baseurl: ""

title: Anthony Knight
description: Introduction

link-tags: true
bigimg: - "/resources/images/sousousvlei_head.png" : "Trees and Sousousvlei Dunes"
