theme: jekyll-theme-hacker
title: teeekay.tknights.com
description: A website for and by Tony Knight 
github:
  repository_name: teeekay.tknights.com
  project_tagline: "About Anthony Knight and some of the Projects he worked on"
  repository_url: http://teeekay.tknights.com
  site_name: teeekay.tknights.com
