theme: jekyll-theme-hacker
title: teeekay.tknights.com
description: A website for and by Tony Knight
favicon: favicon.ico
github:
  repository_name: teeekay
  project_tagline: "About Anthony Knight and some of the Projects he worked on"
  repository_url: https://github.com/teeekay
  site_name: teeekay.tknights.com
